#!/bin/bash
set -e

app_dir=./src

command="$1"
target="$2"

commands=("build" "publish", "test", "help")
targets=("all" "terminal")

declare -A app_targets
app_targets["terminal"]="$app_dir/ServiceRunner.Terminal/ServiceRunner.Terminal.csproj"

function help {
    echo -e "Commands:"
    for i in "${commands[@]}"; do
        echo -e "\t$i"
    done
    echo -e "Targets:"
    for i in "${targets[@]}"; do
        echo -e "\t$i"
    done
    echo -e "Usage: ./run <command>"
    echo -e "Usage: ./run <command> <target>"
}

function search {
    local target="$1"
    shift
    local arr=("$@")

    for i in "${arr[@]}"; do
        if [ "$i" == "$target" ]; then
            return 1
        fi
    done
    return 0
}

if [ "$command" == "help" ]; then
    help
    exit 0
elif [ "$command" == "test" ]; then
    dotnet test
    exit 0
fi

is_command=$(search "$command" "${commands}[@]")
if [ "$command" == "" ] || [ is_command == 0 ]; then
    help
    exit 1
fi

is_target=$(search "$target" "${targets}[@]")
if [ "$target" == "" ] || [ is_target == 0 ]; then
    help
    exit 1
fi

if [ "$target" == "all" ]; then
    for i in "${targets[@]}"; do
        if [ "$i" != "all" ]; then
            ./run "$command" "$i"
        fi
    done
    exit 0
fi

if [ "$command" == "build" ]; then
    dotnet restore "${app_targets[$target]}"
    dotnet msbuild "${app_targets[$target]}"
    exit 0
fi