#!/bin/bash
set -e

source ./scripts/utils/shared

target="$1"

is_target=$(is_in_array "$target" "${targets[@]}")

if [ "$target" == "" ] || [ "$target" == "help" ] || [ "$is_target" == "0" ]; then
    log_targets
    log_usage "build" "<target>"
    exit 1
fi

dotnet restore

if [ "$target" == "all" ]; then
    for i in "${targets[@]}"; do
        if [ "$i" == "all" ]; then
            continue
        fi

        cd "$source_dir/${source_targets[$i]}"
        dotnet msbuild
        cd ../../
    done
else
    cd "$source_dir/${source_targets[$target]}"
    dotnet msbuild
    cd ../../
fi

exit 0